<script>
{/* let name=["Ram","Amit","Ravi","Sumit","Payal","Ravi","Bablu"];
let num=[1,4,7,2,8,3,9,5,6];
document.write(name);
document.write("<br><br>");
document.write(num)

//_1(#Changing Array index value)//
// name[0]="Anmol"
// document.write(name);

//_2(#Deleting array index value)//
// name[0]=null
// delete name[0]
// document.write("<br><br>");
// document.write(name)

//_3(#sorting Array asc)//
// document.write("<br><br>");
// name.sort()
// document.write(name)
// document.write("<br><br>");

//_4(#sorting array in desc)//
// name.reverse()
// document.write(name)

// document.write("<br><br>");

// document.write(num);
document.write("<br><br>");

// document.write(num.sort())
// document.write(num.reverse())

//_5(#Deleting last index of an array)//
// name.pop();
// document.write(name)

//_6(#) adding new value/index at the end of an array )//
// name.push("Riya"); 
// document.write(name)


//_6(# deleting first index/value of an array)//
// name.shift() 
// document.write(name)

//_7(# adding new value/index at the starting of an array )//
// name.unshift("Golu") // 
// document.write(name)

//_8(#joining two array)//
// let new_arr = num.concat(name);
// document.write(new_arr)
// console.log(new_arr)

 */}
//_9(# converting an array into string with delimeter "str1 delimeter str"   --> aman * singh  *==delimeter)//
// let data= name.join(" * ") 
// document.write(data)

//_10(# sicing an array starting form index 2 and ending at index 4)//
// let slice_arr = name.slice(2,5); 
// document.write(slice_arr)

//_11(# adding new array inside / between an existing array)//
//_12(# deleting the index and  adding new array inside / between an existing array)

// name.splice(2,0,["ABCD","XYZ"]) //
// name.splice(2,1,["ABCD","XYZ"]) 
// document.write(name)


// let data="XYZ";

//_13(ecking the variable data type if its an array or not Result: true/false// ch//)
//_14(# checking index of value in an array starting from 0 or at the begining of an array)//
// document.write(Array.isArray(name)); 
// document.write(name.indexOf("Ravi",0))


//_15(# checking index of value in an array starting from 0 or at the end of an array)
// document.write(name.indexOf("Ravi",0)) 
// document.write(name.lastIndexOf('Ravi',0))  // 


//_16(#checking the given value exists or ont in an array // Result true/false//)
// document.write(name.includes("Sumit")); 
// document.write(num.some(check))

{/* // function check(val){ */}
{/* //     return val>=50 */}
{/* // } */}

//_17(#some is used for checking value in an array depending upon function condition.)
let age = [50,100,20,40,60,55,80,150,360];

{/* // let check = age.some(function(val){ */}
{/* //     return val>=18; */}
{/* // }); */}
{/* // document.write(check) */}

{/* //_18(#every is use to check every index of an array based on function condition// */}
{/* // let check= age.every(function(input){ */}
{/* //     return input>=18; */}
{/* // }); */}
{/* // document.write(check) */}
{/* // document.write(age); */}
{/* // document.write("<br>") */}
{/*  */}
{/* // let data = age.filter(function(input){  */}
//         return input>50;
// });

// document.write(data);

//_19(#Returning it self)
//   document.write(age.valueOf(25))

//_20(#converting an array into a string)
// console.log(typeof(name.toString()))

//_21(# fill is used for filling every index of an array with given value)

//    age.fill("A")

// document.write(age)
// 

//_22(# for Rach function)//
// name.forEach(function(data){
//     document.write("Hi, " + data +"<br>")
// });


// num.map(function(data){
// //     document.write(data*10 +"<br>")
// // });

// document.write("<Br>");

// _23(#arr objet)//
// let arr_obj=[
// {"name" : "amit", "age":25,"gender": "male"},
// {"name" : "Sumit", "age":26,"gender": "male"},
// {"name" : "Ganesh", "age":27,"gender": "male"},
// {"name" : "Ravi", "age":28,"gender": "male"},
// {"name" : "Ravita", "age":28,"gender": "female" , "class" : "XII"}
// ];


// for(obj of arr_obj){
// for(index in obj){
// document.write(index + " : " + obj[index] + "<br>");
// }
// document.write("<br>");
// }




</script>