<?php

// echo("Hello World");
// echo "hello World";
// print("Hello World");

#Single Line Comment

/* 
Multi
Line
Comment
*/

// $a="Amit";

// echo $a ;

$a=10;
$b=20;

// echo $a + $b;

// echo "<h1>sdfsd</h1>";


//String

$str="hello World";
// var_dump($str);

//Integer
$num=12;

// var_dump($num);

$dec=5.48485;

// var_dump($dec);

$bool=false;

// var_dump($bool);


//Array

//Indexed Array

$arry=["Amit","Sumit","Ravi","Ankit"];
$arry=array("Amit","Sumit","Ravi","Ankit");

// var_dump($arry);

// echo $arry[0];



//Associative Array

$data=['a'=> 'Apple', 'b'=>"BatMan", 'c'=>"Carrot", 'd'=>'Don'];

echo $data['b'];




?>


<!-- String
1Integer
Float (floating point numbers - also called double)
Boolean
Array -->

33.0